"""Generate the placeholder 'cat' avatar pack from simple shapes (D-6 default).

Deliberately crude pixel art: it exists so M8 lands and the pack format is
exercised end-to-end before the owner's chosen art arrives. Appendix B format.

Run:  .venv/bin/python scripts/make_placeholder_cat.py
"""
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
PACK = ROOT / "avatars" / "cat"
SIZE = 128
BODY = (90, 90, 100, 255)
DARK = (60, 60, 70, 255)
PINK = (230, 140, 150, 255)
WHITE = (240, 240, 245, 255)


def base(ear_lift: int = 0, tilt: int = 0) -> tuple[Image.Image, ImageDraw.ImageDraw]:
    img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    # ears (triangles), lifted when listening
    d.polygon([(28, 58 - ear_lift), (40, 20 - ear_lift), (56, 52 - ear_lift)], fill=BODY)
    d.polygon([(72, 52 - ear_lift), (88, 20 - ear_lift), (100, 58 - ear_lift)], fill=BODY)
    d.polygon([(34, 52 - ear_lift), (41, 30 - ear_lift), (52, 50 - ear_lift)], fill=PINK)
    d.polygon([(76, 50 - ear_lift), (87, 30 - ear_lift), (94, 52 - ear_lift)], fill=PINK)
    # head
    d.ellipse([24, 40 + tilt, 104, 116 + tilt], fill=BODY)
    # eye whites (sockets at (48,72) and (80,72), radius 6 — matches manifest)
    d.ellipse([40, 62 + tilt, 56, 82 + tilt], fill=WHITE)
    d.ellipse([72, 62 + tilt, 88, 82 + tilt], fill=WHITE)
    # nose + mouth
    d.polygon([(60, 88 + tilt), (68, 88 + tilt), (64, 94 + tilt)], fill=PINK)
    return img, d


def save(img: Image.Image, anim: str, idx: int) -> None:
    out = PACK / anim
    out.mkdir(parents=True, exist_ok=True)
    img.save(out / f"{idx:03d}.png")


def main() -> None:
    # idle: subtle breathing (head bob)
    for i, tilt in enumerate((0, 2)):
        img, d = base(tilt=tilt)
        d.arc([56, 92 + tilt, 72, 102 + tilt], 20, 160, fill=DARK, width=2)
        save(img, "idle", i)
    # listening: ears up, mouth small o
    for i, lift in enumerate((10, 12)):
        img, d = base(ear_lift=lift)
        d.ellipse([61, 94, 67, 100], outline=DARK, width=2)
        save(img, "listening", i)
    # thinking: thought dots rising
    for i in range(3):
        img, d = base()
        d.arc([56, 92, 72, 102], 20, 160, fill=DARK, width=2)
        for j in range(i + 1):
            r = 2 + j
            d.ellipse([104 - r, 40 - j * 14 - r, 104 + r, 40 - j * 14 + r], fill=WHITE)
        save(img, "thinking", i)
    # speaking: mouth open/close
    for i, mouth in enumerate((6, 12)):
        img, d = base()
        d.ellipse([58, 92, 70, 92 + mouth], fill=DARK)
        save(img, "speaking", i)
    # error: flat ears, X eyes drawn over whites
    img, d = base(ear_lift=-6)
    for cx in (48, 80):
        d.line([cx - 5, 67, cx + 5, 77], fill=DARK, width=3)
        d.line([cx + 5, 67, cx - 5, 77], fill=DARK, width=3)
    d.line([58, 96, 70, 96], fill=DARK, width=2)
    save(img, "error", 0)
    # blink overlay: eyelids over the sockets
    for i in range(2):
        img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
        d = ImageDraw.Draw(img)
        h = 10 if i == 0 else 20
        d.ellipse([40, 62, 56, 62 + h], fill=BODY)
        d.ellipse([72, 62, 88, 62 + h], fill=BODY)
        save(img, "blink", i)
    # pupil
    pupil = Image.new("RGBA", (10, 10), (0, 0, 0, 0))
    d = ImageDraw.Draw(pupil)
    d.ellipse([0, 0, 9, 9], fill=(30, 30, 40, 255))
    (PACK / "eyes").mkdir(parents=True, exist_ok=True)
    pupil.save(PACK / "eyes" / "pupil.png")

    (PACK / "avatar.yaml").write_text(
        """name: "Cat"
version: 1
author: "placeholder (code-drawn)"
frame_size: [128, 128]
anchor: bottom-center

states:
  idle:      {anim: idle,      fps: 2,  loop: true}
  listening: {anim: listening, fps: 4,  loop: true}
  thinking:  {anim: thinking,  fps: 3,  loop: true}
  speaking:  {anim: speaking,  fps: 6,  loop: true}
  error:     {anim: error,     fps: 1,  loop: false}

fallbacks:
  speaking: idle
  thinking: idle
  listening: idle
  error: idle

overlays:
  blink: {anim: blink, fps: 16, only_in: [idle]}

eyes:
  pupil: eyes/pupil.png
  sockets:
    - {center: [48, 72], radius: 4}
    - {center: [80, 72], radius: 4}
  hide_in: [blink, error]
"""
    )
    (PACK / "LICENSE").write_text(
        "Placeholder art generated by scripts/make_placeholder_cat.py in this repo.\n"
        "CC0 / public domain. Replace with properly licensed art per Appendix B.\n"
    )
    print(f"wrote pack: {PACK}")


if __name__ == "__main__":
    main()
