"""Streaming TTS: Phrase → PcmChunk via Piper (FR6).

Synthesis is per-phrase (sentence-level chunking upstream), so playback of
sentence 1 starts while sentence 2 is still being generated by the LLM.
Blocking ONNX synthesis runs in a worker thread; the loop stays live (P5).
"""
from __future__ import annotations

import asyncio
import logging
from collections.abc import AsyncIterator
from typing import Protocol

from jarvis import config
from jarvis.bus import PcmChunk, Phrase

log = logging.getLogger("jarvis.tts")


class Synthesizer(Protocol):
    """The slice of piper.PiperVoice we use; injectable for tests."""

    def synthesize(self, text: str): ...  # yields chunks with .audio_int16_bytes/.sample_rate


def _load_piper() -> Synthesizer:
    from piper import PiperVoice

    cfg = config.get()["tts"]
    path = config.ROOT / cfg["voices_dir"] / f"{cfg['voice']}.onnx"
    return PiperVoice.load(str(path))


class TextToSpeech:
    def __init__(self, voice: Synthesizer | None = None) -> None:
        self._voice = voice if voice is not None else _load_piper()

    async def synthesize(self, phrase: Phrase) -> AsyncIterator[PcmChunk]:
        """Yield PCM for one phrase; cancellable between chunks (P5)."""
        loop = asyncio.get_running_loop()
        iterator = await loop.run_in_executor(None, self._voice.synthesize, phrase.text)
        iterator = iter(iterator)
        while True:
            chunk = await loop.run_in_executor(None, next, iterator, None)
            if chunk is None:
                return
            yield PcmChunk(
                pcm=chunk.audio_int16_bytes,
                sample_rate=chunk.sample_rate,
                turn_id=phrase.turn_id,
            )
